[project]
authors = ["Luis Pedro Coelho <luis@luispedro.org>"]
channels = ["conda-forge", "bioconda"]
name = "mags_qc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
checkm2 = ">=1.1.0,<2"
jug = ">=2.4.0,<3"
polars = ">=1.30.0,<2"
matplotlib = ">=3.10.3,<4"
ipython = ">=9.3.0,<10"
seaborn = ">=0.13.2,<0.14"
pyqt = ">=5.15.11,<6"
