[project]
authors = ["Luis Pedro Coelho <luis@luispedro.org>"]
channels = ["conda-forge", "bioconda"]
name = "mags_qc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
checkm2 = ">=1.1.0,<2"
